{"name": "Validate login failure with valid username and invalid password -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I navigate to homepage", "status": "passed", "start": 1726872453999, "stop": 1726872454010}, {"name": "When I enter username as \"<userName>\"", "status": "passed", "start": 1726872454010, "stop": 1726872457223}, {"name": "And I enter password as \"<password>\"", "status": "passed", "start": 1726872457223, "stop": 1726872460396}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872460396, "stop": 1726872465685}, {"name": "When I validate the page title", "status": "passed", "start": 1726872465685, "stop": 1726872465968}, {"name": "When I enter username as \"testUser\"", "status": "passed", "start": 1726872465968, "stop": 1726872469177}, {"name": "And I enter password as \"User12345\"", "status": "passed", "start": 1726872469177, "stop": 1726872472356}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872472356, "stop": 1726872477490}, {"name": "Then I verify invalid login error message is displayed", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Screenshot", "source": "54835ce7-bfff-478b-aeca-f14d1ffe6c60-attachment.png", "type": "image/png"}], "start": 1726872477490, "stop": 1726872477885}], "parameters": [{"name": "userName2", "value": "testUser"}, {"name": "password2", "value": "User12345"}], "start": 1726872446111, "stop": 1726872484290, "uuid": "2ee968bf-fa41-4466-921f-f083f2e495c5", "historyId": "8d609fc0337b4b67ddb90f3edfd0a329", "fullName": "Calories Calculation functionality: Validate login failure with valid username and invalid password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "feature", "value": "Calories Calculation functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}