{"name": "Validate login failure with valid username and invalid password -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I navigate to homepage", "status": "passed", "start": 1726872725121, "stop": 1726872725128}, {"name": "When I enter username as \"<userName>\"", "status": "passed", "start": 1726872725129, "stop": 1726872728319}, {"name": "And I enter password as \"<password>\"", "status": "passed", "start": 1726872728321, "stop": 1726872731485}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872731485, "stop": 1726872736567}, {"name": "When I validate the page title", "status": "passed", "start": 1726872736567, "stop": 1726872736572}, {"name": "When I enter username as \"testUser\"", "status": "passed", "start": 1726872736572, "stop": 1726872739727}, {"name": "And I enter password as \"\"", "status": "passed", "start": 1726872739727, "stop": 1726872742830}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872742830, "stop": 1726872747917}, {"name": "Then I verify invalid login error message is displayed", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Screenshot", "source": "046e651c-229b-482b-80b2-f920e7a7dad9-attachment.png", "type": "image/png"}], "start": 1726872747917, "stop": 1726872748111}], "parameters": [{"name": "userName2", "value": "testUser"}, {"name": "password2"}], "start": 1726872717540, "stop": 1726872754568, "uuid": "91b17f0e-0caf-4479-b877-4767faea60b7", "historyId": "a16c277fe2c7af1caa3643c9be748f78", "fullName": "Calories Calculation functionality: Validate login failure with valid username and invalid password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "feature", "value": "Calories Calculation functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}