{"name": "Validate login failure with valid username and invalid password -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I navigate to homepage", "status": "passed", "start": 1726872688212, "stop": 1726872688228}, {"name": "When I enter username as \"<userName>\"", "status": "passed", "start": 1726872688228, "stop": 1726872691375}, {"name": "And I enter password as \"<password>\"", "status": "passed", "start": 1726872691375, "stop": 1726872694502}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872694502, "stop": 1726872699575}, {"name": "When I validate the page title", "status": "passed", "start": 1726872699575, "stop": 1726872699592}, {"name": "When I enter username as \"testUser\"", "status": "passed", "start": 1726872699592, "stop": 1726872702726}, {"name": "And I enter password as \"User12345\"", "status": "passed", "start": 1726872702726, "stop": 1726872705845}, {"name": "And I click on Continue button", "status": "passed", "start": 1726872705845, "stop": 1726872710933}, {"name": "Then I verify invalid login error message is displayed", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error message to be 'The password is incorrect for username testUser' but got 'Invalid login attempt. Please try again.'\n", "trace": "  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sande\\OneDrive\\Desktop\\Shital\\Trustwell\\NewBDDFramework\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert errorMessage == expectedMessage, f\"Expected error message to be '{expectedMessage}' but got '{errorMessage}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Screenshot", "source": "c507de6e-c5f1-43c5-b818-ab234c78c5a6-attachment.png", "type": "image/png"}], "start": 1726872710933, "stop": 1726872711180}], "parameters": [{"name": "userName2", "value": "testUser"}, {"name": "password2", "value": "User12345"}], "start": 1726872680650, "stop": 1726872717535, "uuid": "4e50bad5-b98c-495a-9287-eda1cb27a1cb", "historyId": "8d609fc0337b4b67ddb90f3edfd0a329", "fullName": "Calories Calculation functionality: Validate login failure with valid username and invalid password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "feature", "value": "Calories Calculation functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}